
name: Node.js - E2E, Unit Tests, Lint (for PR) 

on:
  pull_request:
    types: [opened, synchronize, reopened]
      # Trigger when PR is created and/or head of branch is updated.
    paths:
      - "static_report/**"
      - "piperider_cli/**"
      # Trigger when diffs detected in statics source code
    branches:
      - main
      # Only PR target is `main`

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./static_report

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
        cache-dependency-path: static_report/yarn.lock

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: ./static_report
        install-command: yarn --frozen-lockfile --silent

    - name: Prepare Piperider Data & E2E Builds (2+1 runs; 1+1 comparison)
      working-directory: .
      run: |
        pwd
        pip install -r requirements.txt

        which piperider
        piperider version
        
        bash static_report/src/sdlc/generate-e2e-data.sh first

        cd static_report
        npm run embed:html -- e2e
        npm run bundle:e2e:norm
        cd ..

        bash static_report/src/sdlc/generate-e2e-data.sh second

        cd static_report
        npm run embed:html -- e2e
        npm run bundle:e2e:case
        cd ..

    - name: Cypress run (E2E)
    # Parallelization only for cypress dashboard https://www.cypress.io/pricing/
      uses: cypress-io/github-action@v2
      with:
        install: false
        working-directory: ./static_report
        config-file: cypress.config.ts
        start: |
          npm run serve:e2e:norm:single
          npm run serve:e2e:norm:comparison
          npm run serve:e2e:case:single-edge
          npm run serve:e2e:case:comparison-asymmetric
        wait-on: 'http://localhost:3000, http://localhost:3001, http://localhost:4000, http://localhost:4001'

    - name: Build Apps
      run: npm run build