name: E2E tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt-get install expect dejagnu
          mkdir -p ~/.piperider
          cat << EOF > ~/.piperider/profile.yml
          user_id: 00000000000000000000000000000000
          anonymous_tracking: true
          EOF
          pip install -r requirements.txt
          piperider version

      - name: RunTests
        run: |
          cd e2e-tests
          origin=$(pwd)
          echo "current directory is $origin"
          touch testrun.log
          nohup tail -F testrun.log &

          cd $origin
          runtest testsuite/getting-started/001-run.exp

          cd $origin
          runtest testsuite/getting-started/002-compare.exp
          echo "Finish"

          echo "Validate report schema"
          cd $origin
          schema_file=$(find ~ -name "schema.json")
          for run in $(find ~ -name "run.json")
          do
             echo "checking $run"
             tail -20 "$run"
             jsonschema -i "$run" "$schema_file"
          done

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-data
          path: |
            e2e-tests/testsuite
